"use client";

import React, { useEffect, useState } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import toast from "react-hot-toast";
import { LuCopy, LuCheck } from "react-icons/lu";

interface KernelOutputProps {
  outputType: string;
  output: string;
}

function useTypewriter(text: string, speed = 6, step = 5) {
  const [output, setOutput] = useState("");
  useEffect(() => {
    if (!text) {
      return;
    }

    setOutput("");
    let i = 0;
    const interval = setInterval(() => {
      i = Math.min(i + step, text.length);
      setOutput(text.slice(0, i));
      if (i >= text.length) {
        clearInterval(interval);
      }
    }, speed);
    return () => clearInterval(interval);
  }, [text, speed]);
  return output;
}

const KernelOutput = ({ outputType, output }: KernelOutputProps) => {
  const typedOutput = useTypewriter(output, 5, 12);
  const isTyping = typedOutput.length < output.length;

  const copyToClipboard = async (text: string, label?: string) => {
    try {
      await navigator.clipboard.writeText(text);
      toast.success(label ? `${label} copied` : "Copied to clipboard", {
        id: "copy-success",
      });
    } catch (err) {
      toast.error("Failed to copy to clipboard", { id: "copy-error" });
    }
  };

  const getCodeText = (children: React.ReactNode): string => {
    if (Array.isArray(children)) {
      return children.join("");
    }
    return String(children ?? "");
  };

  return (
    <div className="w-full flex flex-col gap-2 px-2 mt-5">
      <div className="flex items-center justify-between px-1">
        <h3 className="text-lg font-semibold text-emerald-300">{outputType}</h3>
        <span className="text-xs text-emerald-400/60">
          Generated by KernelAI
        </span>
      </div>
      <div className="relative w-full max-h-160 overflow-y-auto kernel-scrollbar bg-black/60 backdrop-blur-md rounded-xl border border-emerald-500/90 px-5 py-8 text-emerald-50 text-md leading-relaxed whitespace-normal">
        <button
          onClick={() => copyToClipboard(output, outputType)}
          disabled={isTyping}
          className="absolute flex items-center justify-center gap-1 right-3 top-3 text-xs text-emerald-300 hover:text-emerald-200 transition cursor-pointer border border-gray-800 p-1 rounded-md disabled:opacity-70 disabled:cursor-not-allowed disabled:hover:text-emerald-300"
          type="button"
        >
          <LuCopy />
          <span>Copy All</span>
        </button>
        <ReactMarkdown
          remarkPlugins={[remarkGfm]}
          components={{
            p({ children }) {
              return (
                <p className="text-emerald-50 leading-relaxed">{children}</p>
              );
            },
            strong({ children }) {
              return (
                <strong className="text-emerald-200 font-semibold">
                  {children}
                </strong>
              );
            },
            em({ children }) {
              return <em className="text-emerald-200 italic">{children}</em>;
            },
            ul({ children }) {
              return (
                <ul className="list-disc pl-5 text-emerald-50">{children}</ul>
              );
            },
            ol({ children }) {
              return (
                <ol className="list-decimal pl-5 text-emerald-50">
                  {children}
                </ol>
              );
            },
            li({ children }) {
              return <li className="list-item leading-relaxed">{children}</li>;
            },
            blockquote({ children }) {
              return (
                <blockquote className="border-l-2 border-emerald-500/60 pl-4 text-emerald-200/90 italic">
                  {children}
                </blockquote>
              );
            },
            a({ href, children }) {
              return (
                <a
                  href={href}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-emerald-300 underline underline-offset-2 hover:text-emerald-200 transition"
                >
                  {children}
                </a>
              );
            },
            hr() {
              return <hr className="border-emerald-500/30 my-3" />;
            },
            table({ children }) {
              return (
                <div className="overflow-x-auto kernel-scrollbar">
                  <table className="w-full border border-emerald-500/40 rounded-md text-sm">
                    {children}
                  </table>
                </div>
              );
            },
            thead({ children }) {
              return (
                <thead className="bg-black/70 text-emerald-300">
                  {children}
                </thead>
              );
            },
            tbody({ children }) {
              return <tbody className="text-emerald-50">{children}</tbody>;
            },
            tr({ children }) {
              return (
                <tr className="border-b border-emerald-500/20">{children}</tr>
              );
            },
            th({ children }) {
              return (
                <th className="px-3 py-2 text-left font-semibold">
                  {children}
                </th>
              );
            },
            td({ children }) {
              return <td className="px-3 py-2">{children}</td>;
            },

            code({ className, children }) {
              if (!className) {
                return (
                  <code className="bg-emerald-500/10 text-emerald-300 px-1 rounded">
                    {children}
                  </code>
                );
              }
              return <code className={className}>{children}</code>;
            },

            pre({ children }) {
              if (!React.isValidElement(children)) {
                return null;
              }

              const codeElement = children as React.ReactElement<{
                className?: string;
                children?: React.ReactNode;
              }>;

              const codeText = getCodeText(codeElement.props.children);
              const className = codeElement.props.className;

              return (
                <div className="relative my-3 rounded-lg border border-emerald-500/40 bg-black/80 overflow-hidden">
                  <div className="flex items-center justify-between px-3 py-2 border-b border-emerald-500/30 bg-black/90">
                    <div className="flex items-center gap-1.5">
                      <span className="h-2.5 w-2.5 rounded-full bg-red-500/80" />
                      <span className="h-2.5 w-2.5 rounded-full bg-yellow-400/80" />
                      <span className="h-2.5 w-2.5 rounded-full bg-green-500/80" />
                    </div>
                    <button
                      onClick={() => copyToClipboard(codeText, "Code")}
                      disabled={isTyping}
                      className="flex items-center justify-center gap-1 text-xs text-emerald-300 hover:text-emerald-200 transition cursor-pointer disabled:opacity-70 disabled:cursor-not-allowed disabled:hover:text-emerald-300"
                      type="button"
                    >
                      <LuCopy />
                      <span>Copy</span>
                    </button>
                  </div>
                  <pre className="overflow-x-auto kernel-scrollbar px-4 py-3 text-sm leading-relaxed">
                    <code className={className}>{codeText}</code>
                  </pre>
                </div>
              );
            },
          }}
        >
          {typedOutput}
        </ReactMarkdown>
      </div>
    </div>
  );
};

export default KernelOutput;
